name: CI/CD Demo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build the project (Example)
        run: |
          echo "Building the project..."
          # Add your actual build commands here.
          # For example, if you're building a Python package:
          # python setup.py build

  deploy:
    needs: build  # Only deploy after the build job is successful
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy from the main branch

    steps:
      - name: Deploy (Example)
        run: |
          echo "Deploying the project..."
          # Add your actual deployment commands here.
          # For example, if you're deploying to a web server:
          # scp -r dist/* user@server:/var/www/html
          # Or if you're deploying to a cloud platform:
          # gcloud deploy ...
