name: CI for NEET Predictor

on:
  push:
    branches: [ main ] # Run on pushes to the main branch

jobs:
  test:
    runs-on: ubuntu-latest # Use Ubuntu to run the tests

    steps:
      - uses: actions/checkout@v3 # Get your code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Use a Python 3 version

      - name: Install dependencies
        run: python -m pip install -r requirements.txt # Install your project's dependencies

      - name: Run tests
        run: python -m unittest discover # Run all tests in the 'tests' directory
