name: first demo

on:
  push:
    branches: [main]

jobs:  # Correct: jobs (plural)
  build:  # Correct: colon after build
    runs-on: ubuntu-latest
    steps:  # Correct: Indentation is crucial here!
      - name: check code
        uses: actions/checkout@v4
